version: "3"

services:
  postgres:
    image: postgres
    container_name: db_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Hello123@
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data